var myArray = ["hk","hm","hn","hr","ht","hu","id","ie","il","im","in","iq","is","it","je","jm","jo","jp","ke","kg","kh","ki","km","kn","kp","kr","kw","ky","kz","la","lb","lc","li","lk","lr","ls","lt","lu","lv","ly","ma","mc","md","me","mf","mg","mh","ml","mm","mn","mo","mp","mq","mr","ms","mt","mu","mv","mw","mx","my","mz","na","nc","ne","nf","ng","ni","nl","no","np","nr","nu","nz","om","pa","pe","pf","pg","ph","pk","pl","pm","pn","pr","ps","pt","pw","py","qa","re","ro","rs","ru","rw","sa","sb","sc","sd","se","sg","sh","si","sj","sk","sl","sm","sn","so","sr","ss","st","sv","sx","sy","sz","tc","td","tf","tg","th","tj","tk","tl","tm","tn","to","tr","tt","tv","tw","tz","ua","ug","um","us","uy","uz","va","vc","ve","vg","vi","vn","vu","wf","ws","xk","ye","yt","za","zm","zw","ad","ae","af","ag","ai","al","am","ao","aq","ar","as","at","au","aw","ax","az","ba","bb","bd","be","bf","bg","bh","bi","bj","bl","bm","bn","bo","bq","br","bs","bt","bv","bw","by","bz","ca","cc","cd","cf","cg","ch","ck","cl","cm","cn","co","cr","cu","cv","cw","cx","cy","cz","de","dj","dk","dm","do","dz","ec","ee","eg","eh","er","es","et","fi","fj","fk","fm","fo","fr","ga","gb","gb-eng","gb-nir","gb-sct","gb-wls","gd","ge","gf","gg","gh","gi","gl","gm","gn","gp","gq","gr","gs","gt","gu","gw","gy"];
var flagMap = maMap();

function maMap(){
    var maMap = new Map();
	
maMap.set('Afghanistan', 'AF');
maMap.set('Afrique du Sud', 'ZA');
maMap.set('Åland, Îles', 'AX');
maMap.set('Albanie', 'AL');
maMap.set('Algérie', 'DZ');
maMap.set('Allemagne', 'DE');
maMap.set('Andorre', 'AD');
maMap.set('Angola', 'AO');
maMap.set('Anguilla', 'AI');
maMap.set('Antarctique', 'AQ');
maMap.set('Antigua et Barbuda', 'AG');
maMap.set('Antilles néerlandaises', 'AN');
maMap.set('Arabie Saoudite', 'SA');
maMap.set('Argentine', 'AR');
maMap.set('Arménie', 'AM');
maMap.set('Aruba', 'AW');
maMap.set('Australie', 'AU');
maMap.set('Autriche', 'AT');
maMap.set('Azerbaïdjan', 'AZ');
maMap.set('Bahamas', 'BS');
maMap.set('Bahrein', 'BH');
maMap.set('Bangladesh', 'BD');
maMap.set('Barbade', 'BB');
maMap.set('Bélarus', 'BY');
maMap.set('Belgique', 'BE');
maMap.set('Bélize', 'BZ');
maMap.set('Bénin', 'BJ');
maMap.set('Bermudes', 'BM');
maMap.set('Bhoutan', 'BT');
maMap.set('Bolivie (État plurinational de);', 'BO');
maMap.set('Bonaire, Saint-Eustache et Saba', 'BQ');
maMap.set('Bosnie-Herzégovine', 'BA');
maMap.set('Botswana', 'BW');
maMap.set('Bouvet, Ile', 'BV');
maMap.set('Brésil', 'BR');
maMap.set('Brunéi Darussalam', 'BN');
maMap.set('Bulgarie', 'BG');
maMap.set('Burkina Faso', 'BF');
maMap.set('Burundi', 'BI');
maMap.set('Cabo Verde', 'CV');
maMap.set('Caïmans, Iles', 'KY');
maMap.set('Cambodge', 'KH');
maMap.set('Cameroun', 'CM');
maMap.set('Canada', 'CA');
maMap.set('Chili', 'CL');
maMap.set('Chine', 'CN');
maMap.set('Christmas, île', 'CX');
maMap.set('Chypre', 'CY');
maMap.set('Cocos/Keeling (Îles);', 'CC');
maMap.set('Colombie', 'CO');
maMap.set('Comores', 'KM');
maMap.set('Congo', 'CG');
maMap.set('Congo, République démocratique du', 'CD');
maMap.set('Cook, Iles', 'CK');
maMap.set('Corée, République de', 'KR');
maMap.set('Corée, République populaire démocratique de', 'KP');
maMap.set('Costa Rica', 'CR');
maMap.set('Croatie', 'HR');
maMap.set('Cuba', 'CU');
maMap.set('Curaçao', 'CW');
maMap.set('Danemark', 'DK');
maMap.set('Djibouti', 'DJ');
maMap.set('Dominicaine, République', 'DO');
maMap.set('Dominique', 'DM');
maMap.set('Egypte', 'EG');
maMap.set('El Salvador', 'SV');
maMap.set('Emirats arabes unis', 'AE');
maMap.set('Equateur', 'EC');
maMap.set('Erythrée', 'ER');
maMap.set('Espagne', 'ES');
maMap.set('Estonie', 'EE');
maMap.set('Etats-Unis', 'US');
maMap.set('Ethiopie', 'ET');
maMap.set('Falkland/Malouines (Îles);', 'FK');
maMap.set('Féroé, îles', 'FO');
maMap.set('Fidji', 'FJ');
maMap.set('Finlande', 'FI');
maMap.set('France', 'FR');
maMap.set('Gabon', 'GA');
maMap.set('Gambie', 'GM');
maMap.set('Géorgie', 'GE');
maMap.set('Géorgie du sud et les îles Sandwich du sud', 'GS');
maMap.set('Ghana', 'GH');
maMap.set('Gibraltar', 'GI');
maMap.set('Grèce', 'GR');
maMap.set('Grenade', 'GD');
maMap.set('Groenland', 'GL');
maMap.set('Guadeloupe', 'GP');
maMap.set('Guam', 'GU');
maMap.set('Guatemala', 'GT');
maMap.set('Guernesey', 'GG');
maMap.set('Guinée', 'GN');
maMap.set('Guinée-Bissau', 'GW');
maMap.set('Guinée équatoriale', 'GQ');
maMap.set('Guyana', 'GY');
maMap.set('Guyane française', 'GF');
maMap.set('Haïti', 'HT');
maMap.set('Heard, Ile et MacDonald, îles', 'HM');
maMap.set('Honduras', 'HN');
maMap.set('Hong Kong', 'HK');
maMap.set('Hongrie', 'HU');
maMap.set('Île de Man', 'IM');
maMap.set('Îles mineures éloignées des Etats-Unis', 'UM');
maMap.set('Îles vierges britanniques', 'VG');
maMap.set('Îles vierges des Etats-Unis', 'VI');
maMap.set('Inde', 'IN');
maMap.set('Indonésie', 'ID');
maMap.set('Iraq', 'IQ');
maMap.set('Irlande', 'IE');
maMap.set('Islande', 'IS');
maMap.set('Israël', 'IL');
maMap.set('Italie', 'IT');
maMap.set('Jamaïque', 'JM');
maMap.set('Japon', 'JP');
maMap.set('Jersey', 'JE');
maMap.set('Jordanie', 'JO');
maMap.set('Kazakhstan', 'KZ');
maMap.set('Kenya', 'KE');
maMap.set('Kirghizistan', 'KG');
maMap.set('Kiribati', 'KI');
maMap.set('Koweït', 'KW');
maMap.set('Lao, République démocratique populaire', 'LA');
maMap.set('Lesotho', 'LS');
maMap.set('Lettonie', 'LV');
maMap.set('Liban', 'LB');
maMap.set('Libéria', 'LR');
maMap.set('Libye', 'LY');
maMap.set('Liechtenstein', 'LI');
maMap.set('Lituanie', 'LT');
maMap.set('Luxembourg', 'LU');
maMap.set('Macao', 'MO');
maMap.set('Madagascar', 'MG');
maMap.set('Malaisie', 'MY');
maMap.set('Malawi', 'MW');
maMap.set('Maldives', 'MV');
maMap.set('Mali', 'ML');
maMap.set('Malte', 'MT');
maMap.set('Mariannes du nord, Iles', 'MP');
maMap.set('Maroc', 'MA');
maMap.set('Marshall, Iles', 'MH');
maMap.set('Martinique', 'MQ');
maMap.set('Maurice', 'MU');
maMap.set('Mauritanie', 'MR');
maMap.set('Mayotte', 'YT');
maMap.set('Mexique', 'MX');
maMap.set('Micronésie, Etats Fédérés de', 'FM');
maMap.set('Moldova, République de', 'MD');
maMap.set('Monaco', 'MC');
maMap.set('Mongolie', 'MN');
maMap.set('Monténégro', 'ME');
maMap.set('Montserrat', 'MS');
maMap.set('Mozambique', 'MZ');
maMap.set('Myanmar', 'MM');
maMap.set('Namibie', 'NA');
maMap.set('Nauru', 'NR');
maMap.set('Népal', 'NP');
maMap.set('Nicaragua', 'NI');
maMap.set('Niger', 'NE');
maMap.set('Nigéria', 'NG');
maMap.set('Niue', 'NU');
maMap.set('Norfolk, Ile', 'NF');
maMap.set('Norvège', 'NO');
maMap.set('Nouvelle);lédonie', 'NC');
maMap.set('Nouvelle-Zélande', 'NZ');
maMap.set('Oman', 'OM');
maMap.set('Ouganda', 'UG');
maMap.set('Ouzbékistan', 'UZ');
maMap.set('Pakistan', 'PK');
maMap.set('Palaos', 'PW');
maMap.set('Palestine, Etat de', 'PS');
maMap.set('Panama', 'PA');
maMap.set('Papouasie-Nouvelle-Guinée', 'PG');
maMap.set('Paraguay', 'PY');
maMap.set('Pays-Bas', 'NL');
maMap.set('Pays inconnu', 'XX');
maMap.set('Pays multiples', 'ZZ');
maMap.set('Pérou', 'PE');
maMap.set('Philippines', 'PH');
maMap.set('Pitcairn', 'PN');
maMap.set('Pologne', 'PL');
maMap.set('Polynésie française', 'PF');
maMap.set('Porto Rico', 'PR');
maMap.set('Portugal', 'PT');
maMap.set('Qatar', 'QA');
maMap.set('République arabe syrienne', 'SY');
maMap.set('République centrafricaine', 'CF');
maMap.set('Réunion', 'RE');
maMap.set('Roumanie', 'RO');
maMap.set('Royaume-Uni', 'GB');
maMap.set('Russie, Fédération de', 'RU');
maMap.set('Rwanda', 'RW');
maMap.set('Sahara occidental', 'EH');
maMap.set('Saint-Barthélemy', 'BL');
maMap.set('Saint-Kitts-et-Nevis', 'KN');
maMap.set('Saint-Marin', 'SM');
maMap.set('Saint-Martin (partie française);', 'MF');
maMap.set('Saint-Martin (partie néerlandaise);', 'SX');
maMap.set('Saint-Pierre-et-Miquelon', 'PM');
maMap.set('Saint-Siège', 'VA');
maMap.set('Saint-Vincent-et-les-Grenadines', 'VC');
maMap.set('Sainte-Hélène, Ascension et Tristan da Cunha', 'SH');
maMap.set('Sainte-Lucie', 'LC');
maMap.set('Salomon, Iles', 'SB');
maMap.set('Samoa', 'WS');
maMap.set('Samoa américaines', 'AS');
maMap.set('Sao Tomé-et-Principe', 'ST');
maMap.set('Sénégal', 'SN');
maMap.set('Serbie', 'RS');
maMap.set('Seychelles', 'SC');
maMap.set('Sierra Leone', 'SL');
maMap.set('Singapour', 'SG');
maMap.set('Slovaquie', 'SK');
maMap.set('Slovénie', 'SI');
maMap.set('Somalie', 'SO');
maMap.set('Soudan', 'SD');
maMap.set('Soudan du Sud', 'SS');
maMap.set('Sri Lanka', 'LK');
maMap.set('Suède', 'SE');
maMap.set('Suisse', 'CH');
maMap.set('Suriname', 'SR');
maMap.set('Svalbard et île Jan Mayen', 'SJ');
maMap.set('Swaziland', 'SZ');
maMap.set('Tadjikistan', 'TJ');
maMap.set('Taïwan, Province de Chine', 'TW');
maMap.set('Tanzanie, République unie de', 'TZ');
maMap.set('Tchad', 'TD');
maMap.set('Tchécoslovaquie', 'CS');
maMap.set('Tchèque, République', 'CZ');
maMap.set('Terres australes françaises', 'TF');
maMap.set('Thaïlande', 'TH');
maMap.set('Timor-Leste', 'TL');
maMap.set('Togo', 'TG');
maMap.set('Tokelau', 'TK');
maMap.set('Tonga', 'TO');
maMap.set('Trinité-et-Tobago', 'TT');
maMap.set('Tunisie', 'TN');
maMap.set('Turkménistan', 'TM');
maMap.set('Turks-et);ïcos (Îles);', 'TC');
maMap.set('Turquie', 'TR');
maMap.set('Tuvalu', 'TV');
maMap.set('Ukraine', 'UA');
maMap.set('URSS', 'SU');
maMap.set('Uruguay', 'UY');
maMap.set('Vanuatu', 'VU');
maMap.set('Vatican : voir Saint-Siège', '');
maMap.set('Venezuela (République bolivarienne du);', 'VE');
maMap.set('Viet Nam', 'VN');
maMap.set('Viet Nam (Sud);', 'VD');
maMap.set('Wallis et Futuna', 'WF');
maMap.set('Yémen', 'YE');
maMap.set('Yougoslavie', 'YU');
maMap.set('Zaïre', 'ZR');
maMap.set('Zambie', 'ZM');
maMap.set('Zimbabwe', 'ZW)';
    
    return maMap;
    };
	
